modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/quat1024/packages/issues"

[[mods]]
modId="packages"
version="${version}"
displayName="Packages"
displayURL="https://github.com/quat1024/packages/"
logoFile="packages-icon.png"
authors="quaternary"
description="The opinionated storage mod. Worse Barrels descendant. Now on Forge!"

[[dependencies.packages]]
modId="minecraft"
mandatory=true
versionRange="1.19.2"
ordering="NONE"
side="BOTH"
